name: Adhoc Deploy latest Builds
on:
  workflow_dispatch:
    inputs:
      SplacePlanning_Build_Version:
        description: "SpacePlanning Application Version"
        required: true
jobs:
  deploy-latest-builds:
    runs-on: ubuntu-latest
    steps:
      - name: Login to jFrog Artifactory
        uses: jfrog/setup-jfrog-cli@v2
        with:
          url: ${{ secrets.JFROG_URL }}
          user: ${{ secrets.JFROG_USER}}
          pass: ${{ secrrts.JFROG_PASSWORD}}