name: Adhoc Deploy latest Builds
on:
  workflow_dispatch:
    inputs:
      SplacePlanning_Build_Version:
        description: "SpacePlanning Application Version"
        required: true
      Application_name:
        description: "Application name"
        required: true
jobs:
  deploy-latest-builds:
    runs-on: ubuntu-latest
    steps:
      - name: Login to jFrog Artifactory
        uses: jfrog/setup-jfrog-cli@v2
        with:
          url: ${{ secrets.JFROG_URL }}
          user: ${{ secrets.JFROG_USER}}
          pass: ${{ secrets.JFROG_PASSWORD}}
      - name: Download artifacts
        shell: pwsh
        run: |

          $executionPath = (Get-Item -Path ".\").FullName
          Write-Host "Initial execution path - $executionPath"
          cd..

          $rootDir = (Get-Item -Path ".\").FullName
          Write-Host "Root path - $rootDir"

          $Folder= "$rootDir/spaceplanning"

          If (!(test-path $Folder)) {
          New-Item -ItemType Directory -Path $Folder}

          Write-Host "Artifacts path - $Folder"
      
          $downloadPath= "microservices-release-local/com/jda/microservice/catman/installs/$Application_name/$Application_name-$SplacePlanning_Build_Version.tgz"

          jfrog rt dl $downloadPath  "$Folder/" --flat=true 
          Write-Host "Files Downloaded"